# Validate this file using http://lint.travis-ci.org/
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
git:
  submodules: false
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libhdf5-serial-dev
  - pip install pytest
  - pip install cython  # Temporary fix https://github.com/LUMC/kPAL/issues/1
install: pip install .
script: py.test
